apiVersion: catalog.kubevault.com/v1alpha1
kind: VaultServerVersion
metadata:
  name: '1.2.3'
  labels:
    {{- include "kubevault-catalog.labels" . | nindent 4 }}
spec:
  exporter:
    image: '{{ include "image.ghcr" (merge (dict "_repo" "kubevault/vault-exporter") $) }}:v0.1.1'
  initContainer:
    image: '{{ include "image.dockerLibrary" (merge (dict "_repo" "busybox") $) }}'
  stash:
    addon:
      backupTask:
        name: vault-backup-1.10.3
      restoreTask:
        name: vault-restore-1.10.3
  unsealer:
    image: '{{ include "image.dockerHub" (merge (dict "_repo" "kubevault/vault-unsealer") $) }}:v0.20.0'
  vault:
    image: '{{ include "image.ghcr" (merge (dict "_repo" "appscode-images/vault") $) }}:1.2.3'
  version: 1.2.3
