apiVersion: metrics.appscode.com/v1alpha1
kind: MetricsConfiguration
metadata:
  name: catalog-kubevault-com-vaultserverversion
spec:
  targetRef:
    apiVersion: catalog.kubevault.com/v1alpha1
    kind: VaultServerVersion
  metrics:
    - name: created
      help: "Unix creation timestamp"
      type: gauge
      field:
        path: .metadata.creationTimestamp
        type: DateTime
      metricValue:
        valueFromPath: .metadata.creationTimestamp

    - name: info
      help: "VaultServer versions info"
      type: gauge
      labels:
        - key: deprecated
          valuePath: .spec.deprecated
        - key: vault_image
          valuePath: .spec.vault.image
        - key: unsealer_image
          valuePath: .spec.unsealer.image
      metricValue:
        value: 1
