# kubectl patch deploy vault-operator -n kube-system --patch "$(cat run-on-master.yaml)"
spec:
  template:
    spec:
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
