{{- $caCrt := "" }}
{{- $serverCrt := "" }}
{{- $serverKey := "" }}
{{- if .Values.apiserver.servingCerts.generate }}
{{- $ca := genCA "ca" 3650 }}
{{- $cn := include "kubevault-webhook-server.fullname" . -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $server := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
{{- $caCrt =  b64enc $ca.Cert }}
{{- $serverCrt = b64enc $server.Cert }}
{{- $serverKey = b64enc $server.Key }}
{{- else }}
{{- $caCrt = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.caCrt }}
{{- $serverCrt = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.serverCrt }}
{{- $serverKey = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.serverKey }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevault-webhook-server.fullname" . }}-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $caCrt }}
  tls.crt: {{ $serverCrt }}
  tls.key: {{ $serverKey }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.validators.kubevault.com
  labels:
    app.kubernetes.io/component: kubevault-core
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
spec:
  group: validators.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ include "kubevault-webhook-server.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.mutators.kubevault.com
  labels:
    app.kubernetes.io/component: kubevault-core
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
spec:
  group: mutators.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ include "kubevault-webhook-server.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.validators.engine.kubevault.com
  labels:
    app.kubernetes.io/component: kubevault-engine
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
spec:
  group: validators.engine.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ include "kubevault-webhook-server.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.mutators.engine.kubevault.com
  labels:
    app.kubernetes.io/component: kubevault-engine
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
spec:
  group: mutators.engine.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ include "kubevault-webhook-server.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.mutators.policy.kubevault.com
  labels:
    app.kubernetes.io/component: kubevault-policy
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
spec:
  group: mutators.policy.kubevault.com
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ include "kubevault-webhook-server.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
