apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubevault-webhook-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
  {{- if eq "prometheus.io/builtin" ( include "monitoring.agent" . ) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: {{ .Values.apiserver.port | quote }}
    prometheus.io/scheme: "https"
  {{- end }}
spec:
  ports:
  - name: operator
    port: 443
    targetPort: operator
  selector:
    {{- include "kubevault-webhook-server.selectorLabels" . | nindent 4 }}
