apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubevault-webhook-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
  {{- if eq "prometheus.io/builtin" ( include "monitoring.agent" . ) }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: {{ .Values.monitoring.bindPort | quote }}
    prometheus.io/scheme: "http"
  {{- end }}
spec:
  ports:
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: webhook
  - name: metrics
    port: {{ .Values.monitoring.bindPort }}
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "kubevault-webhook-server.selectorLabels" . | nindent 4 }}
