{{- if and (eq "prometheus.io/operator" ( include "monitoring.agent" . )) .Values.monitoring.serviceMonitor.bearerToken.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "monitoring.servicemonitor-bearer-token-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "monitoring.servicemonitor-bearer-token-serviceaccount-name" . }}
    {{- with .Values.monitoring.serviceMonitor.bearerToken.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
