{{- if eq "prometheus.io/operator" ( include "monitoring.agent" . ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" (include "kubevault-webhook-server.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevault-webhook-server.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "kubevault-webhook-server.serviceAccountName" . }}
type: kubernetes.io/service-account-token
{{- end }}
