apiVersion: catalog.kubevault.com/v1alpha1
kind: VaultServerVersion
metadata:
  name: 1.5.9
spec:
  exporter:
    image: kubevault/vault-exporter:v0.1.0
  unsealer:
    image: kubevault/vault-unsealer:v0.4.0
  vault:
    image: vault:1.5.9
  version: 1.5.9
