apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
  labels:
    app.kubernetes.io/name: kubevault
  name: vaultserverversions.catalog.kubevault.com
spec:
  group: catalog.kubevault.com
  names:
    categories:
    - vault
    - appscode
    kind: VaultServerVersion
    listKind: VaultServerVersionList
    plural: vaultserverversions
    shortNames:
    - vsv
    singular: vaultserverversion
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.vault.image
      name: VAULT_IMAGE
      type: string
    - jsonPath: .spec.deprecated
      name: Deprecated
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              deprecated:
                type: boolean
              exporter:
                properties:
                  image:
                    type: string
                  imagePullPolicy:
                    type: string
                required:
                - image
                type: object
              initContainer:
                properties:
                  image:
                    type: string
                  imagePullPolicy:
                    type: string
                required:
                - image
                type: object
              stash:
                properties:
                  addon:
                    properties:
                      backupTask:
                        properties:
                          name:
                            type: string
                          params:
                            items:
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                      restoreTask:
                        properties:
                          name:
                            type: string
                          params:
                            items:
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                    required:
                    - backupTask
                    - restoreTask
                    type: object
                type: object
              unsealer:
                properties:
                  image:
                    type: string
                  imagePullPolicy:
                    type: string
                required:
                - image
                type: object
              vault:
                properties:
                  image:
                    type: string
                  imagePullPolicy:
                    type: string
                required:
                - image
                type: object
              version:
                type: string
            required:
            - unsealer
            - vault
            - version
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
