apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: kubevault
  name: vaultserverversions.catalog.kubevault.com
spec:
  group: catalog.kubevault.com
  names:
    categories:
    - vault
    - appscode
    kind: VaultServerVersion
    listKind: VaultServerVersionList
    plural: vaultserverversions
    shortNames:
    - vsv
    singular: vaultserverversion
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.version
      name: Version
      type: string
    - jsonPath: .spec.vault.image
      name: VAULT_IMAGE
      type: string
    - jsonPath: .spec.deprecated
      name: Deprecated
      type: boolean
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: VaultServerVersionSpec is the spec for postgres version
            properties:
              deprecated:
                description: Deprecated versions usable but regarded as obsolete and
                  best avoided, typically due to having been superseded.
                type: boolean
              exporter:
                description: Exporter Image
                properties:
                  image:
                    description: Image is the Docker image name
                    type: string
                  imagePullPolicy:
                    description: ImagePullPolicy one of Always, Never, IfNotPresent.
                      It defaults to Always if :latest is used, or IfNotPresent otherwise.
                    type: string
                required:
                - image
                type: object
              stash:
                description: Stash defines backup and restore task definitions.
                properties:
                  addon:
                    description: StashTaskSpec is the spec for app
                    properties:
                      backupTask:
                        description: Backup task definition
                        properties:
                          name:
                            type: string
                          params:
                            description: Params specifies a list of parameter to pass
                              to the Task. Stash will use this parameters to resolve
                              the task.
                            items:
                              description: Param declares a value to use for the Param
                                called Name.
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                      restoreTask:
                        description: Restore task definition
                        properties:
                          name:
                            type: string
                          params:
                            description: Params specifies a list of parameter to pass
                              to the Task. Stash will use this parameters to resolve
                              the task.
                            items:
                              description: Param declares a value to use for the Param
                                called Name.
                              properties:
                                name:
                                  type: string
                                value:
                                  type: string
                              required:
                              - name
                              - value
                              type: object
                            type: array
                        required:
                        - name
                        type: object
                    required:
                    - backupTask
                    - restoreTask
                    type: object
                type: object
              unsealer:
                description: Unsealer Image
                properties:
                  image:
                    description: Image is the Docker image name
                    type: string
                  imagePullPolicy:
                    description: ImagePullPolicy one of Always, Never, IfNotPresent.
                      It defaults to Always if :latest is used, or IfNotPresent otherwise.
                    type: string
                required:
                - image
                type: object
              vault:
                description: Vault Image
                properties:
                  image:
                    description: Image is the Docker image name
                    type: string
                  imagePullPolicy:
                    description: ImagePullPolicy one of Always, Never, IfNotPresent.
                      It defaults to Always if :latest is used, or IfNotPresent otherwise.
                    type: string
                required:
                - image
                type: object
              version:
                description: Version
                type: string
            required:
            - unsealer
            - vault
            - version
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
