apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: kubevault
  name: secretengines.engine.kubevault.com
spec:
  group: engine.kubevault.com
  names:
    categories:
    - vault
    - appscode
    - all
    kind: SecretEngine
    listKind: SecretEngineList
    plural: secretengines
    singular: secretengine
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              aws:
                properties:
                  credentialSecret:
                    type: string
                  iamEndpoint:
                    type: string
                  leaseConfig:
                    properties:
                      lease:
                        type: string
                      leaseMax:
                        type: string
                    required:
                    - lease
                    - leaseMax
                    type: object
                  maxRetries:
                    format: int64
                    type: integer
                  region:
                    type: string
                  stsEndpoint:
                    type: string
                required:
                - credentialSecret
                - region
                type: object
              azure:
                properties:
                  credentialSecret:
                    type: string
                  environment:
                    type: string
                required:
                - credentialSecret
                type: object
              defaultLeaseTTL:
                type: string
              elasticsearch:
                properties:
                  allowedRoles:
                    items:
                      type: string
                    type: array
                  caCert:
                    type: string
                  caPath:
                    type: string
                  clientCert:
                    type: string
                  clientKey:
                    type: string
                  databaseRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      parameters:
                        type: object
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - name
                    - namespace
                    type: object
                  insecure:
                    default: false
                    type: boolean
                  password:
                    type: string
                  pluginName:
                    type: string
                  tlsServerName:
                    type: string
                  url:
                    type: string
                  username:
                    type: string
                required:
                - databaseRef
                type: object
              gcp:
                properties:
                  credentialSecret:
                    type: string
                  maxTTL:
                    type: string
                  ttl:
                    type: string
                required:
                - credentialSecret
                type: object
              kv:
                properties:
                  casRequired:
                    type: boolean
                  deleteVersionsAfter:
                    type: string
                  maxVersions:
                    format: int64
                    type: integer
                  version:
                    format: int64
                    type: integer
                type: object
              mariadb:
                properties:
                  allowedRoles:
                    items:
                      type: string
                    type: array
                  databaseRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      parameters:
                        type: object
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - name
                    - namespace
                    type: object
                  maxConnectionLifetime:
                    type: string
                  maxIdleConnections:
                    format: int64
                    type: integer
                  maxOpenConnections:
                    format: int64
                    type: integer
                  pluginName:
                    type: string
                required:
                - databaseRef
                type: object
              maxLeaseTTL:
                type: string
              mongodb:
                properties:
                  allowedRoles:
                    items:
                      type: string
                    type: array
                  databaseRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      parameters:
                        type: object
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - name
                    - namespace
                    type: object
                  pluginName:
                    type: string
                  writeConcern:
                    type: string
                required:
                - databaseRef
                type: object
              mysql:
                properties:
                  allowedRoles:
                    items:
                      type: string
                    type: array
                  databaseRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      parameters:
                        type: object
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - name
                    - namespace
                    type: object
                  maxConnectionLifetime:
                    type: string
                  maxIdleConnections:
                    format: int64
                    type: integer
                  maxOpenConnections:
                    format: int64
                    type: integer
                  pluginName:
                    type: string
                required:
                - databaseRef
                type: object
              pki:
                properties:
                  additionalPayload:
                    additionalProperties:
                      type: string
                    type: object
                  altNames:
                    type: string
                  commonName:
                    type: string
                  country:
                    type: string
                  isRootCA:
                    type: boolean
                  issuerName:
                    type: string
                  maxPathLength:
                    type: integer
                  organization:
                    type: string
                  ou:
                    type: string
                  parentCARef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    type: object
                  ttl:
                    type: string
                  type:
                    type: string
                  urls:
                    properties:
                      crlDistributionPoints:
                        items:
                          type: string
                        type: array
                      enableTemplating:
                        type: boolean
                      issuingCertificates:
                        items:
                          type: string
                        type: array
                      ocspServers:
                        items:
                          type: string
                        type: array
                    type: object
                required:
                - isRootCA
                type: object
              postgres:
                properties:
                  allowedRoles:
                    items:
                      type: string
                    type: array
                  databaseRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      parameters:
                        type: object
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - name
                    - namespace
                    type: object
                  maxConnectionLifetime:
                    type: string
                  maxIdleConnections:
                    format: int64
                    type: integer
                  maxOpenConnections:
                    format: int64
                    type: integer
                  pluginName:
                    type: string
                required:
                - databaseRef
                type: object
              redis:
                properties:
                  allowedRoles:
                    items:
                      type: string
                    type: array
                  databaseRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                      parameters:
                        type: object
                        x-kubernetes-embedded-resource: true
                        x-kubernetes-preserve-unknown-fields: true
                    required:
                    - name
                    - namespace
                    type: object
                  pluginName:
                    type: string
                required:
                - databaseRef
                type: object
              vaultRef:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
            required:
            - vaultRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    severity:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
              path:
                type: string
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
