apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    app.kubernetes.io/name: kubevault
  name: azureroles.engine.kubevault.com
spec:
  group: engine.kubevault.com
  names:
    categories:
    - vault
    - appscode
    - all
    kind: AzureRole
    listKind: AzureRoleList
    plural: azureroles
    singular: azurerole
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Status
      type: string
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            properties:
              applicationObjectID:
                type: string
              azureRoles:
                type: string
              maxTTL:
                type: string
              secretEngineRef:
                properties:
                  name:
                    default: ""
                    type: string
                type: object
                x-kubernetes-map-type: atomic
              ttl:
                type: string
            required:
            - secretEngineRef
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      type: string
                    observedGeneration:
                      format: int64
                      type: integer
                    reason:
                      type: string
                    severity:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                  - lastTransitionTime
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                format: int64
                type: integer
              phase:
                type: string
              policyRef:
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                type: object
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
