apiVersion: v2
name: kubevault-opscenter
description: KubeVault Opscenter by AppsCode
type: application
version: v2024.9.30
appVersion: v2024.9.30
home: https://kubevault.com
icon: https://cdn.appscode.com/images/products/kubevault/kubevault-icon.png
sources:
- https://github.com/kubevault
maintainers:
- name: appscode
  email: support@appscode.com
dependencies:
- name: kubevault-metrics
  repository: file://../kubevault-metrics
  condition: kubevault-metrics.enabled
  version: v2024.9.30
- name: kubevault-grafana-dashboards
  repository: file://../kubevault-grafana-dashboards
  condition: kubevault-grafana-dashboards.enabled
  version: v2024.9.30
