{{- $caCrt := "" }}
{{- $serverCrt := "" }}
{{- $serverKey := "" }}
{{- if .Values.apiserver.servingCerts.generate }}
{{- $ca := genCA "ca" 3650 }}
{{- $cn := include "secrets-store-reader.fullname" . -}}
{{- $altName1 := printf "%s.%s" $cn .Release.Namespace }}
{{- $altName2 := printf "%s.%s.svc" $cn .Release.Namespace }}
{{- $server := genSignedCert $cn nil (list $altName1 $altName2) 3650 $ca }}
{{- $caCrt =  b64enc $ca.Cert }}
{{- $serverCrt = b64enc $server.Cert }}
{{- $serverKey = b64enc $server.Key }}
{{- else }}
{{- $caCrt = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.caCrt }}
{{- $serverCrt = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.serverCrt }}
{{- $serverKey = required "Required when apiserver.servingCerts.generate is false" .Values.apiserver.servingCerts.serverKey }}
{{- end }}
# register as aggregated apiserver
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.reader.secrets-store.csi.x-k8s.io
  labels:
    {{- include "secrets-store-reader.labels" . | nindent 4 }}
spec:
  group: reader.secrets-store.csi.x-k8s.io
  version: v1alpha1
  service:
    namespace: {{ .Release.Namespace }}
    name: {{ include "secrets-store-reader.fullname" . }}
  caBundle: {{ $caCrt }}
  groupPriorityMinimum: {{ .Values.apiserver.groupPriorityMinimum }}
  versionPriority: {{ .Values.apiserver.versionPriority }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secrets-store-reader.fullname" . }}-apiserver-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-store-reader.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $serverCrt }}
  tls.key: {{ $serverKey }}
---
# to read the config for terminating authentication
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "secrets-store-reader.fullname" . }}-apiserver-extension-server-authentication-reader
  namespace: kube-system
  labels:
    {{- include "secrets-store-reader.labels" . | nindent 4 }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: extension-apiserver-authentication-reader
subjects:
- kind: ServiceAccount
  name: {{ include "secrets-store-reader.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
---
# to delegate authentication and authorization
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "secrets-store-reader.fullname" . }}-apiserver-auth-delegator
  labels:
    {{- include "secrets-store-reader.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: {{ include "secrets-store-reader.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
