apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "secrets-store-reader.fullname" . }}
  labels:
    {{- include "secrets-store-reader.labels" . | nindent 4 }}
rules:
- apiGroups:
  - reader.secrets-store.csi.x-k8s.io
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - secrets-store.csi.x-k8s.io
  resources:
  - secretproviderclasses
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
