apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "secrets-store-reader.fullname" . }}
  labels:
    {{- include "secrets-store-reader.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "secrets-store-reader.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "secrets-store-reader.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
