apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubevault-operator.fullname" . }}
  labels:
    {{- include "kubevault-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs: ["create", "patch", "list", "get"]
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs: ["get"]
- apiGroups:
  - kubevault.com
  - catalog.kubevault.com
  - engine.kubevault.com
  - policy.kubevault.com
  - appcatalog.appscode.com
  - ops.kubevault.com
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - kubevault.com
  resources:
  - vaultservers/finalizers
  verbs: ["update"]
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ["create", "get", "list", "watch", "patch", "delete"]
- apiGroups:
  - apps
  resources:
  - statefulsets/finalizers
  verbs: ["update"]
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs: ["create", "get", "patch"]
- apiGroups:
    - ""
  resources:
    - serviceaccounts/finalizers
  verbs: ["update"]
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs: ["watch", "create", "get", "patch", "delete", "list"]
- apiGroups:
  - ""
  resources:
  - services/finalizers
  verbs: ["update"]
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs: ["create", "get", "list", "watch", "patch"]
- apiGroups:
  - ""
  resources:
  - nodes
  verbs: ["get", "list", "watch"]
- apiGroups:
  - ""
  resources:
  - events
  verbs: ["create"]
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs: [ "get", "list"]
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs: ["*"]
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/eviction
  verbs: ["get", "create", "list"]
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  - roles
  - rolebindings
  verbs: ["get", "update", "create", "patch", "delete"]
- apiGroups:
  - cert-manager.io
  resources:
  - "*"
  verbs: ["*"]
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs: ["create"]
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs: ["get", "list", "create", "delete", "patch", "deletecollection"]
- apiGroups:
  - supervisor.appscode.com
  resources: ["*"]
  verbs: ["create", "get", "list", "watch", "update", "patch"]
