apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubevault-operator.fullname" . }}-license-checker
  labels:
    {{- include "kubevault-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: appscode:license-checker
subjects:
- kind: ServiceAccount
  name: {{ include "kubevault-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
