apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubevault-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubevault-operator.labels" . | nindent 4 }}
  {{- if and (eq .Values.monitoring.agent "prometheus.io/builtin") .Values.monitoring.enabled }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: {{ .Values.apiserver.port | quote }}
    prometheus.io/scheme: "https"
  {{- end }}
spec:
  ports:
  - name: metrics
    port: {{ .Values.monitoring.bindPort }}
    targetPort: metrics
  selector:
    {{- include "kubevault-operator.selectorLabels" . | nindent 4 }}
