{{- if and (eq .Values.monitoring.agent "prometheus.io/operator") .Values.monitoring.operator }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kubevault-operator.fullname" . }}
  namespace: {{ default .Release.Namespace  .Values.monitoring.prometheus.namespace }}
  labels:
    {{- if .Values.monitoring.serviceMonitor.labels }}
    {{- range $key, $val := .Values.monitoring.serviceMonitor.labels }}
    {{ $key }}: {{ $val }}
    {{- end }}
    {{- else }}
      {{- include "kubevault-operator.selectorLabels" . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "kubevault-operator.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: api
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    scheme: https
    tlsConfig:
      caFile: /etc/prometheus/secrets/{{ include "kubevault-operator.fullname" . }}-apiserver-cert/tls.crt
      serverName: "{{ include "kubevault-operator.fullname" . }}.{{ .Release.Namespace }}.svc"
{{- end }}
