kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# the control plane node
- role: control-plane
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
- role: worker
  extraMounts:
    - containerPath: /opt/local-path-provisioner
      hostPath: /mnt
      readOnly: false
kubeadmConfigPatches:
- |
  kind: MasterConfiguration
  apiServerExtraArgs:
    "feature-gates": "DynamicProvisioningScheduling=true"
  controllerManagerExtraArgs:
    "feature-gates": "DynamicProvisioningScheduling=true"
  schedulerExtraArgs:
    "feature-gates": "DynamicProvisioningScheduling=true"
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "DynamicProvisioningScheduling=true"
  kubeProxy:
    config:
      featureGates:
        DynamicProvisioningScheduling: true
- |
  kind: NodeConfiguration
  nodeRegistration:
    kubeletExtraArgs:
      "feature-gates": "DynamicProvisioningScheduling=true"
