properties:
  fullnameOverride:
    type: string
  image:
    properties:
      registry:
        type: string
    required:
    - registry
    type: object
  nameOverride:
    type: string
required:
- image
type: object
