{{ if .object.spec.deprecated }}
{{- "{{ if (not .Values.skipDeprecated) }}" -}}
{{ end -}}
apiVersion: {{ .object.apiVersion }}
kind: {{ .object.kind }}
metadata:
  name: '{{ .object.metadata.name }}'
  labels:
    {{"{{- include \"kubevault-catalog.labels\" . | nindent 4 }}"}}
spec:
  {{- .object.spec | toYaml | nindent 2 }}
{{ if .object.spec.deprecated }}
{{"{{ end }}"}}
{{ end }}