apiVersion: v1
description: KubeVault Catalog by AppsCode - Catalog for KubeVault supported versions
name: kubevault-catalog
version: v2022.09.22
appVersion: v2022.09.22
home: https://kubevault.com
icon: https://cdn.appscode.com/images/products/kubevault/icons/android-icon-192x192.png
sources:
- https://github.com/kubevault
maintainers:
- name: appscode
  email: support@appscode.com
