apiVersion: v1
description: 'Vault Catalog by AppsCode - Catalog for Vault versions'
name: kubevault-catalog
version: v0.4.0-alpha.0
appVersion: v0.4.0-alpha.0
home: https://kubevault.com
icon: https://cdn.appscode.com/images/products/kubevault/icons/android-icon-192x192.png
sources:
- https://github.com/kubevault
maintainers:
- name: appscode
  email: support@appscode.com
