project:
  name: KubeVault Catalog by AppsCode
  shortName: KubeVault Catalog
  url: https://github.com/kubevault/operator
  description: Catalog for KubeVault supported versions supported by KubeVault
  app: HashiCorp KubeVault Catalog
repository:
  url: https://charts.appscode.com/stable/
  name: appscode
chart:
  name: kubevault-catalog
  values: -- generate from values file --
  valuesExample: -- generate from values file --
prerequisites:
- Kubernetes 1.16+
release:
  name: kubevault-catalog
  namespace: kubevault
