# needed for StatefulSet
kind: Service
apiVersion: v1
metadata:
  name: {{ include "csi-vault.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4}}
    app.kubernetes.io/component: {{ .Values.components.controller }}
  {{- if and (eq .Values.monitoring.agent "prometheus.io/builtin") .Values.monitoring.controller }}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8443"
    prometheus.io/scheme: "https"
{{- end }}
spec:
  selector:
    {{- include "csi-vault.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.components.controller }}
  ports:
  - name: api
    port: 443
    targetPort: 8443

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "csi-vault.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.components.controller }}

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-vault.controller.fullname" . }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.components.controller }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["list", "watch", "create", "update", "patch"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshots"]
  verbs: ["get", "list"]
- apiGroups: ["snapshot.storage.k8s.io"]
  resources: ["volumesnapshotcontents"]
  verbs: ["get", "list"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csidrivers", "csinodeinfos"]
  verbs: ["get", "watch", "list", "update", "patch", "create"]
- apiGroups: ["authorization.k8s.io"]
  resources: ["subjectaccessreviews"]
  verbs: ["get", "create"]
- apiGroups: ["authentication.k8s.io"]
  resources: ["tokenreviews"]
  verbs: ["get", "create"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["*"]
---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-vault.controller.fullname" . }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.components.controller }}
subjects:
- kind: ServiceAccount
  name: {{ include "csi-vault.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
    kind: ClusterRole
    name: {{ include "csi-vault.controller.fullname" . }}
    apiGroup: rbac.authorization.k8s.io

---

# Attacher must be able to work with PVs, nodes and VolumeAttachments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-vault.attacher.fullname" . }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.components.controller }}
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["csi.storage.k8s.io"]
  resources: ["csidrivers", "csinodeinfos"]
  verbs: ["get", "watch", "list", "update", "patch", "create"]
- apiGroups: ["storage.k8s.io"]
  resources: ["volumeattachments"]
  verbs: ["get", "list", "watch", "update"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "list", "watch", "delete"]
- apiGroups: ["appcatalog.appscode.com"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "csi-vault.attacher.fullname" . }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.components.controller }}
subjects:
- kind: ServiceAccount
  name: {{ include "csi-vault.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
    kind: ClusterRole
    name: {{ include "csi-vault.attacher.fullname" . }}
    apiGroup: rbac.authorization.k8s.io

---

{{- $major := default "0" .Capabilities.KubeVersion.Major | trimSuffix "+" | int64 }}
{{- $minor := default "0" .Capabilities.KubeVersion.Minor | trimSuffix "+" | int64 }}
{{- $criticalAddon := and .Values.criticalAddon (or (eq .Release.Namespace "kube-system") (and (ge $major 1) (ge $minor 17))) -}}
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "csi-vault.controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "csi-vault.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ .Values.components.controller }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  serviceName: {{ include "csi-vault.controller.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "csi-vault.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.components.controller }}
  template:
    metadata:
      labels:
        {{- include "csi-vault.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.components.controller }}
      annotations:
        checksum/apiserver-cert.yaml: {{ include (print $.Template.BasePath "/apiserver-cert.yaml") . | sha256sum }}
      {{- if $criticalAddon }}
        scheduler.alpha.kubernetes.io/critical-pod: ''
      {{- end }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccount: {{ include "csi-vault.controller.fullname" . }}
      containers:
      - name: csi-provisioner
        securityContext:
          {{- toYaml .Values.provisioner.securityContext | nindent 10 }}
        image: {{ .Values.provisioner.registry}}/{{ .Values.provisioner.repository}}:{{ .Values.provisioner.tag }}
        args:
        - --csi-address={{ .Values.pluginAddress}}
        - --v={{ .Values.logLevel }}
        imagePullPolicy: {{ .Values.provisioner.pullPolicy }}
        resources:
              {{ toYaml .Values.resources | indent 10 }}
        resources:
          {{- toYaml .Values.provisioner.resources | nindent 10 }}
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.pluginDir }}
      - name: csi-attacher
        securityContext:
          {{- toYaml .Values.attacher.securityContext | nindent 10 }}
        image: {{ .Values.attacher.registry}}/{{ .Values.attacher.repository }}:{{ .Values.attacher.tag }}
        args:
        - --v={{ .Values.logLevel }}
        - --csi-address={{ .Values.pluginAddress}}
        imagePullPolicy: {{ .Values.attacher.pullPolicy }}
        resources:
          {{- toYaml .Values.attacher.resources | nindent 10 }}
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.pluginDir }}
      - name: csi-vault-plugin
        securityContext:
          {{- toYaml .Values.plugin.securityContext | nindent 10 }}
        image: {{ .Values.plugin.registry }}/{{ .Values.plugin.repository }}:{{ .Values.plugin.tag }}
        args :
        - run
        - --csi-address=unix:{{ .Values.pluginAddress }}
        - --node=$(NODE_NAME)
        - --v={{ .Values.logLevel }}
        - --secure-port=8443
        - --tls-cert-file=/var/serving-cert/tls.crt
        - --tls-private-key-file=/var/serving-cert/tls.key
        - --use-kubeapiserver-fqdn-for-aks={{ .Values.apiserver.useKubeapiserverFqdnForAks }}
        - --enable-analytics={{ .Values.enableAnalytics }}
        ports:
        - containerPort: 8443
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        imagePullPolicy: {{ .Values.plugin.pullPolicy }}
      {{- if .Values.apiserver.healthcheck.enabled }}
        livenessProbe:
          httpGet:
            port: 8443
            path: /healthz
            scheme: HTTPS
          initialDelaySeconds: 10
      {{- end }}
        resources:
          {{- toYaml .Values.plugin.resources | nindent 10 }}
        volumeMounts:
        - name: socket-dir
          mountPath: {{ .Values.pluginDir }}
        - name: serving-cert
          mountPath: /var/serving-cert
      volumes:
      - name: socket-dir
        emptyDir: {}
      - name: serving-cert
        secret:
          defaultMode: 420
          secretName: {{ include "csi-vault.fullname" . }}-apiserver-cert
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if or .Values.tolerations $criticalAddon }}
      tolerations:
      {{- with .Values.tolerations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $criticalAddon }}
        - key: CriticalAddonsOnly
          operator: Exists
      {{- end -}}
    {{- end -}}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $criticalAddon }}
      priorityClassName: system-cluster-critical
    {{- end -}}
