apiVersion: v1
description: KubeVault Operator by AppsCode - HashiCorp Vault operator for Kubernetes
name: kubevault-operator
version: v0.18.0
appVersion: v0.18.1
home: https://kubevault.com
icon: https://cdn.appscode.com/images/products/kubevault/icons/android-icon-192x192.png
sources:
- https://github.com/kubevault
maintainers:
- name: appscode
  email: support@appscode.com
