name: CI

on:
  push:
    branches-ignore:
      - 'release-*'
    tags-ignore:
      - '*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run checks
      run: |
        sudo apt-get -qq update || true
        sudo apt-get install -y bzr
        curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubectl
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/kubectl
        make ci

  kubernetes:
    name: Kubernetes
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        cluster:
        - {"version": "v1.11.10", "config": "kind-1.11.yaml"}
        - {"version": "v1.12.10", "config": "kind.yaml"}
        - {"version": "v1.13.10", "config": "kind.yaml"}
        - {"version": "v1.14.6", "config": "kind.yaml"}
        - {"version": "v1.15.3", "config": "kind.yaml"}
        - {"version": "v1.16.3", "config": "kind.yaml"}
        - {"version": "v1.17.0", "config": "kind.yaml"}
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Create Kubernetes ${{ matrix.cluster.version }} cluster
      id: kind
      uses: engineerd/setup-kind@v0.1.0
      with:
        version: v0.7.0
        config: hack/kubernetes/${{ matrix.cluster.config }}
        image: kindest/node:${{ matrix.cluster.version }}

    - name: Prepare cluster for testing
      id: local-path
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        USERNAME: 1gtm
        REGISTRY_SECRET: regcred
      run: |
        echo "waiting for nodes to be ready ..."
        kubectl wait --for=condition=Ready nodes --all --timeout=5m
        kubectl get nodes
        echo
        kubectl version
        echo
        echo "installing local-path provisioner ..."
        kubectl delete storageclass --all
        kubectl apply -f https://github.com/rancher/local-path-provisioner/raw/v0.0.12/deploy/local-path-storage.yaml
        kubectl wait --for=condition=Ready pods -n local-path-storage --all --timeout=5m
        kubectl apply -f hack/kubernetes/storageclass/standard.yaml
        echo
        echo "create docker-registry secret"
        kubectl create secret docker-registry ${REGISTRY_SECRET} --namespace=kube-system --docker-server=https://index.docker.io/v1/ --docker-username=${USERNAME} --docker-password=${DOCKER_TOKEN}

    - name: Test vault-operator chart
      run: |
        export KUBECONFIG="${HOME}/.kube/config"
        make ct TEST_CHARTS=charts/vault-operator
        echo
        kubectl delete crds --all
        kubectl apply -f https://github.com/kubevault/operator/raw/master/api/crds/catalog.kubevault.com_vaultserverversions.yaml --validate=false
        kubectl wait --for=condition=NamesAccepted crds --all --timeout=5m
        make ct TEST_CHARTS=charts/vault-catalog
        echo
        kubectl delete crds --all

    - name: Test csi-vault chart
      if: (matrix.cluster.version != 'v1.11.10') && (matrix.cluster.version != 'v1.12.10') && (matrix.cluster.version != 'v1.13.10')
      run: |
        export KUBECONFIG="${HOME}/.kube/config"
        make ct TEST_CHARTS=charts/csi-vault
